import { Talent } from "../../scripts/extractTalents/types";

export const snowQueen: Talent[] = [
    {
        "code": "ice_clone",
        "name": "Ice Clone",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Defense_Clone.png",
        "type": "starting",
        "unlockedAtRank": 1,
        "description": [
            "{sk}DEFENSE{/s} leaves an ice clone with {sk}40%{/s} of Hero's Maximum Health, attracting enemies' attention",
            "When destroyed or after {sk}10{/s} seconds have passed, it deals {si}40{/s} area damage and inflicts {sk}CHILLED{/s} to enemies hit"
        ],
        "improvements": [
            [
                "40"
            ],
            [
                "60"
            ],
            [
                "80"
            ],
            [
                "100"
            ]
        ]
    },
    {
        "code": "rupture",
        "name": "Rupture",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Trait_Quest.png",
        "type": "starting",
        "unlockedAtRank": 1,
        "description": [
            "{sk}Quest (x20):{/s} {sk}SHATTER{/s} {sk}2{/s} enemies with a single {sk}TRAIT{/s} to earn {sk}+0.5 DMG{/s}",
            "{sk}Complete{/s}: {sk}SHATTER{/s} leaves affected enemies {sk}VULNERABLE{/s} for {si}4{/s} seconds"
        ],
        "improvements": [
            [
                "4"
            ],
            [
                "5"
            ],
            [
                "6"
            ],
            [
                "7"
            ]
        ]
    },
    {
        "code": "frost_queen",
        "name": "Frost Queen",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Passive_Better_Frost.png",
        "type": "starting",
        "unlockedAtRank": 2,
        "description": [
            "Frost generated by your abilities remains on the ground for {si}2{/s} seconds",
            "{sk}CHILLED{/s} effects slow enemies by an additional {sk}20%{/s}"
        ],
        "improvements": [
            [
                "2"
            ],
            [
                "3"
            ],
            [
                "4"
            ],
            [
                "5"
            ]
        ]
    },
    {
        "code": "dual_lances",
        "name": "Dual Lances",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Attack_Dual.png",
        "type": "starting",
        "unlockedAtRank": 5,
        "description": [
            "{sk}ATTACK{/s} sends forth two lances side by side but their maximum range is reduced by {sd}45%{/s}",
            "Each lance deals {si}70%{/s} damage"
        ],
        "improvements": [
            [
                "70%"
            ],
            [
                "80%"
            ],
            [
                "90%"
            ],
            [
                "100%"
            ]
        ]
    },
    {
        "code": "snowball",
        "name": "Snowball",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Power_Snowball.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}POWER{/s} sends a snowball that deals {si}20{/s} damage per second to enemies in its path and inflicts them with {sk}CHILLED{/s}",
            "Each enemy hit reduces the size and damage of the snowball by {sd}12%{/s}"
        ],
        "improvements": [
            [
                "20"
            ],
            [
                "25"
            ],
            [
                "30"
            ],
            [
                "35"
            ]
        ]
    },
    {
        "code": "windy_lances",
        "name": "Windy Lances",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Attack_Seeking.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}ATTACK{/s}'s lances can curve to seek out targets, and their duration resets whenever they hit an enemy, up to {si}3{/s} times"
        ],
        "improvements": [
            [
                "3"
            ],
            [
                "4"
            ],
            [
                "5"
            ],
            [
                "6"
            ]
        ]
    },
    {
        "code": "lance_burst",
        "name": "Lance Burst",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Trait_Sends_Attacks.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}TRAIT{/s} sends {si}3{/s} {sk}ATTACKS{/s} forward in a cone-shaped burst"
        ],
        "improvements": [
            [
                "3"
            ],
            [
                "4"
            ],
            [
                "5"
            ],
            [
                "6"
            ]
        ]
    },
    {
        "code": "slide",
        "name": "Slide",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Dash_Frost.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}DASH{/s} creates frost underfoot, dealing {si}100%{/s} of {sk}DEFENSE{/s} damage to enemies passed"
        ],
        "improvements": [
            [
                "100%"
            ],
            [
                "125%"
            ],
            [
                "150%"
            ],
            [
                "175%"
            ]
        ]
    },
    {
        "code": "flurry_of_shards",
        "name": "Flurry of Shards",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Special_Extra_Waves.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}SPECIAL{/s} can be held to hit up to {si}2{/s} more time(s)"
        ],
        "improvements": [
            [
                "2"
            ],
            [
                "3"
            ],
            [
                "4"
            ],
            [
                "5"
            ]
        ]
    },
    {
        "code": "hailstorm",
        "name": "Hailstorm",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Power_Ice_Waves.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "After using {sk}POWER{/s}, {si}3{/s} waves of ice strike the area and deal {sk}20{/s} damage each"
        ],
        "improvements": [
            [
                "3"
            ],
            [
                "4"
            ],
            [
                "5"
            ],
            [
                "6"
            ]
        ]
    },
    {
        "code": "frost_surge",
        "name": "Frost Surge",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Power_Hold.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "{sk}POWER{/s} can be held to store up to {sk}3{/s} levels of charge before being released",
            "Each charge level increases damage dealt by {si}20%{/s} and the effect radius by {sk}10%{/s}"
        ],
        "improvements": [
            [
                "20%"
            ],
            [
                "25%"
            ],
            [
                "30%"
            ],
            [
                "35%"
            ]
        ]
    },
    {
        "code": "cold_heart",
        "name": "Cold Heart",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Passive_Chilled_Crit.png",
        "type": "standard",
        "unlockedAtRank": 1,
        "description": [
            "Gain {si}+4%{/s} Crit Chance for each {sk}CHILLED{/s} enemy nearby (can stack up to {sk}5{/s} times)"
        ],
        "improvements": [
            [
                "+4%"
            ],
            [
                "+5%"
            ],
            [
                "+6%"
            ],
            [
                "+7%"
            ]
        ]
    },
    {
        "code": "radiant_crown",
        "name": "Radiant Crown",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Trait_Charge.png",
        "type": "standard",
        "unlockedAtRank": 2,
        "description": [
            "Gain {sk}+1 TRAIT charge{/s}",
            "Any Shatter effect deals {si}+20%{/s} damage"
        ],
        "improvements": [
            [
                "+20%"
            ],
            [
                "+25%"
            ],
            [
                "+30%"
            ],
            [
                "+35%"
            ]
        ]
    },
    {
        "code": "strafe",
        "name": "Strafe",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Defense_Sends_Attacks.png",
        "type": "standard",
        "unlockedAtRank": 3,
        "description": [
            "{sk}DEFENSE{/s} sends up to {si}5{/s} successive {sk}ATTACKS{/s} to nearby enemies"
        ],
        "improvements": [
            [
                "5"
            ],
            [
                "6"
            ],
            [
                "7"
            ],
            [
                "8"
            ]
        ]
    },
    {
        "code": "ice_spray",
        "name": "Ice Spray",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Special_Double.png",
        "type": "standard",
        "unlockedAtRank": 3,
        "description": [
            "{sk}SPECIAL{/s} sprays two bursts of ice shards in opposite directions, dealing {si}+20%{/s} damage to {sk}CHILLED{/s} enemies."
        ],
        "improvements": [
            [
                "+20%"
            ],
            [
                "+25%"
            ],
            [
                "+30%"
            ],
            [
                "+35%"
            ]
        ]
    },
    {
        "code": "ice_shield",
        "name": "Ice Shield",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Defense_Shield.png",
        "type": "standard",
        "unlockedAtRank": 4,
        "description": [
            "{sk}DEFENSE{/s} grants a {si}16{/s} SHIELD to The Snow Queen and all Heroes passed for {sk}6{/s} seconds"
        ],
        "improvements": [
            [
                "16"
            ],
            [
                "20"
            ],
            [
                "24"
            ],
            [
                "28"
            ]
        ]
    },
    {
        "code": "shattering_blast",
        "name": "Shattering Blast",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Power_Shatter.png",
        "type": "standard",
        "unlockedAtRank": 4,
        "description": [
            "{sk}POWER{/s} triggers {sk}SHATTER{/s} when hitting enemies that are already {sk}CHILLED{/s}",
            "Each {sk}SHATTER{/s} deals {si}+20%{/s} damage"
        ],
        "improvements": [
            [
                "+20%"
            ],
            [
                "+25%"
            ],
            [
                "+30%"
            ],
            [
                "+35%"
            ]
        ]
    },
    {
        "code": "freezing_stars",
        "name": "Freezing Stars",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Dash_Freeze_Trap.png",
        "type": "standard",
        "unlockedAtRank": 5,
        "description": [
            "{sk}DASH{/s} leaves behind an ice star that explodes due to a Shattering effect or after {sk}10{/s} seconds",
            "The ice star's explosion deals {si}32{/s} area damage and inflicts {sk}CHILLED{/s} to enemies hit"
        ],
        "improvements": [
            [
                "32"
            ],
            [
                "40"
            ],
            [
                "48"
            ],
            [
                "56"
            ]
        ]
    },
    {
        "code": "protective_crown",
        "name": "Protective Crown",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Trait_Shield.png",
        "type": "standard",
        "unlockedAtRank": 7,
        "description": [
            "{sk}TRAIT{/s} grants {si}4{/s} {sk}SHIELD{/s} for {sk}6{/s} seconds to all Heroes around for each enemy hit (up to {sk}4{/s} times)"
        ],
        "improvements": [
            [
                "4"
            ],
            [
                "5"
            ],
            [
                "6"
            ],
            [
                "7"
            ]
        ]
    },
    {
        "code": "ice_cores",
        "name": "Ice Cores",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Special_Icicles.png",
        "type": "standard",
        "unlockedAtRank": 7,
        "description": [
            "Each enemy hit by {sk}POWER{/s} summons a core of ice (up to {sk}6{/s})",
            "The {sk}SPECIAL{/s} consumes each core to fire an {sk}ATTACK{/s} dealing {si}80%{/s} damage"
        ],
        "improvements": [
            [
                "80%"
            ],
            [
                "100%"
            ],
            [
                "120%"
            ],
            [
                "140%"
            ]
        ]
    },
    {
        "code": "pirouette",
        "name": "Pirouette",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Defense_Final.png",
        "type": "standard",
        "unlockedAtRank": 8,
        "description": [
            "Retriggering {sk}DEFENSE{/s} while it is in progress triggers a spin dealing {si}40{/s} area damage, {sk}+50%{/s} to {sk}CHILLED{/s} enemies"
        ],
        "improvements": [
            [
                "40"
            ],
            [
                "50"
            ],
            [
                "60"
            ],
            [
                "70"
            ]
        ]
    },
    {
        "code": "frostbite",
        "name": "Frostbite",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Passive_Damage_To_Chilled.png",
        "type": "standard",
        "unlockedAtRank": 8,
        "description": [
            "All abilities that deal extra damage to {sk}CHILLED{/s} enemies deal {si}+20%{/s} extra damage"
        ],
        "improvements": [
            [
                "+20%"
            ],
            [
                "+25%"
            ],
            [
                "+30%"
            ],
            [
                "+35%"
            ]
        ]
    },
    {
        "code": "royal_ray",
        "name": "Royal Ray",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Ultimate_1_Casts_Trait.png",
        "type": "final",
        "unlockedAtRank": 1,
        "description": [
            "{sk}ULTIMATE{/s} triggers {sk}TRAIT{/s} at its start and deals {si}+8%{/s} damage for each shattered enemy (up to {sk}+40%{/s})"
        ],
        "improvements": [
            [
                "+8%"
            ],
            [
                "+10%"
            ],
            [
                "+12%"
            ],
            [
                "+14%"
            ]
        ]
    },
    {
        "code": "rending_storm",
        "name": "Rending Storm",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Ultimate_2_Ability_Blast.png",
        "type": "final",
        "unlockedAtRank": 6,
        "description": [
            "Each time The Snow Queen casts {sk}TRAIT{/s}, {sk}POWER{/s} or {sk}SPECIAL{/s} within the {sk}ULTIMATE{/s} zone, the storm unleashes a burst dealing {si}20{/s} damage"
        ],
        "improvements": [
            [
                "20"
            ],
            [
                "25"
            ],
            [
                "30"
            ],
            [
                "35"
            ]
        ]
    },
    {
        "code": "ice_beam",
        "name": "Ice Beam",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Ultimate_1_Ice_Beam.png",
        "type": "final",
        "unlockedAtRank": 9,
        "description": [
            "{sk}ULTIMATE{/s} now channels an ice beam, dealing {si}160%{/s} damage and inflicting {sk}CHILLED{/s} to first enemy hit"
        ],
        "improvements": [
            [
                "160%"
            ],
            [
                "200%"
            ],
            [
                "240%"
            ],
            [
                "280%"
            ]
        ]
    },
    {
        "code": "shattering_storm",
        "name": "Shattering Storm",
        "iconUrl": "http://dt-live-3.passtechgames.com:8080/heroes/the_snow_queen/Skill_Ultimate_2_Shatter.png",
        "type": "final",
        "unlockedAtRank": 9,
        "description": [
            "When {sk}ULTIMATE{/s} effect ends, zone explodes and {sk}SHATTERS{/s} all enemies insides, dealing {si}72{/s} damage"
        ],
        "improvements": [
            [
                "72"
            ],
            [
                "90"
            ],
            [
                "108"
            ],
            [
                "126"
            ]
        ]
    }
];